kind: pipeline
name: default
steps:
- name: check
  image: ubuntu:latest
  commands:
  - add-apt-repository ppa:kelleyk/emacs -y
  - apt-get update
  - apt-get install -y emacs26
  - emacs --version
  - make ci-dependencies
  - make check
